#! /bin/bash -x

#The -t flag is removed because it is not supported on ppc64le archictecture on travis and throws a error "The input device is not a TTY"
container_id=$(
    docker run -d -i -v `pwd`:/workdir:Z -u $(id -u) registry.fedoraproject.org/fedora bash
    )

cleanup ()
{
    docker rm --force "$container_id"
}

trap cleanup EXIT

run_in_container ()
{
    local uid=$(id -u)
    if ${as_root-false}; then
        uid=0
    fi
#The -t flag is removed because it is not supported on ppc64le archictecture on travis and throws a error "The input device is not a TTY" 
    docker exec -u $uid -i "$container_id" "$@"
}

buildrequires='
autoconf-archive
automake
help2man
elinks
findutils
docbook-utils
postgresql-devel
postgresql-server
make
'

as_root=true \
run_in_container bash -c "dnf install -y $(echo $buildrequires)"
run_in_container bash -c "set -x ; cd /workdir && ./.travis/distcheck"
